name: Build and deploy Next.js (standalone) to Azure Web App - githubapp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (standalone)
        run: npm run build

      - name: Prepare deploy artifact
        run: |
          rm -rf deploy && mkdir -p deploy
          # Copia el runtime standalone generado por Next
          cp -r .next/standalone/* deploy/
          # Copia estáticos y public
          mkdir -p deploy/.next/static
          cp -r .next/static deploy/.next/static
          if [ -d public ]; then cp -r public deploy/public; fi
          # Copia package.json (para npm start en Azure si hiciera falta)
          cp package.json deploy/package.json
          # Crea un server.js “puente” dentro del artefacto
          cat > deploy/server.js <<'EOF'
          // Puente para garantizar ruta correcta
          require('./.next/standalone/server.js');
          EOF

      - name: Zip artifact
        run: cd deploy && zip -r ../app.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CFCE9F62CEA24FF588FFB293C29B9721 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_48838789205A4457B3E0F688EABA40F0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E3F09A8579CE4E2AB76244D9E44D167F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: githubapp
          slot-name: Production
          package: app.zip
